server_tokens off;

map $sent_http_content_type $expires_by_type {
    default off;
    text/html 1m;
    text/css 30d;
    application/javascript 30d;
    application/pdf 30d;
    image/png 365d;
    image/jpeg 365d;
    image/webp 365d;
    image/svg+xml 365d;
    font/woff 365d;
    font/woff2 365d;
}

gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_min_length 1024;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
